In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks

In [4]:
# Reading the Dataset
dataset = pd.read_csv('50_Startups.csv')

In [5]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [6]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [7]:
datasets

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False
5,131876.90,99814.71,362861.36,156991.12,False,True
6,134615.46,147198.87,127716.82,156122.51,False,False
7,130298.13,145530.06,323876.68,155752.60,True,False
8,120542.52,148718.95,311613.29,152211.77,False,True
9,123334.88,108679.17,304981.62,149759.96,False,False
10,101913.08,110594.11,229160.95,146121.95,True,False
11,100671.96,91790.61,249744.55,144259.40,False,False
12,93863.75,127320.38,249839.44,141585.52,True,False
13,91992.39,135495.07,252664.93,134307.35,False,False
14,119943.24,156547.42,256512.92,132602.65,True,False
15,114523.61,122616.84,261776.23,129917.04,False,True
16,78013.11,121597.55,264346.06,126992.93,False,False
17,94657.16,145077.58,282574.31,125370.37,False,True
18,91749.16,114175.79,294919.57,124266.90,True,False
19,86419.70,153514.11,0.00,122776.86,False,True
20,76253.86,113867.30,298664.47,118474.03,False,False
21,78389.47,153773.43,299737.29,111313.02,False,True
22,73994.56,122782.75,303319.26,110352.25,True,False
23,67532.53,105751.03,304768.73,108733.99,True,False
24,77044.01,99281.34,140574.81,108552.04,False,True
25,64664.71,139553.16,137962.62,107404.34,False,False
26,75328.87,144135.98,134050.07,105733.54,True,False
27,72107.60,127864.55,353183.81,105008.31,False,True
28,66051.52,182645.56,118148.20,103282.38,True,False
29,65605.48,153032.06,107138.38,101004.64,False,True
30,61994.48,115641.28,91131.24,99937.59,True,False
31,61136.38,152701.92,88218.23,97483.56,False,True
32,63408.86,129219.61,46085.25,97427.84,False,False
33,55493.95,103057.49,214634.81,96778.92,True,False
34,46426.07,157693.92,210797.67,96712.80,False,False
35,46014.02,85047.44,205517.64,96479.51,False,True
36,28663.76,127056.21,201126.82,90708.19,True,False
37,44069.95,51283.14,197029.42,89949.14,False,False
38,20229.59,65947.93,185265.10,81229.06,False,True
39,38558.51,82982.09,174999.30,81005.76,False,False
40,28754.33,118546.05,172795.67,78239.91,False,False
41,27892.92,84710.77,164470.71,77798.83,True,False
42,23640.93,96189.63,148001.11,71498.49,False,False
43,15505.73,127382.30,35534.17,69758.98,False,True
44,22177.74,154806.14,28334.72,65200.33,False,False
45,1000.23,124153.04,1903.93,64926.08,False,True
46,1315.46,115816.21,297114.46,49490.75,True,False
47,0.00,135426.92,0.00,42559.73,False,False
48,542.05,51743.15,0.00,35673.41,False,True
49,0.00,116983.80,45173.06,14681.40,False,False

In [8]:
indep=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dep=datasets[['Profit']]

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.svm import SVR
regressor=SVR(kernel="linear",C=0.1)
regressor=regressor.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [11]:
y_pred=regressor.predict(X_test)

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [13]:
r_score

0.9198778403618616

In [14]:
regressor.intercept_

array([41221.60593222])

In [15]:
regressor.n_support_

array([33], dtype=int32)

In [16]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype=int32)

In [17]:
regressor.support_vectors_

array([[1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 0.0000000e+00,
        1.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [6.5605480e+04, 1.5303206e+05, 1.0713838e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.1452361e+05, 1.2261684e+05, 2.6177623e+05, 0.0000000e+00,
        1.0000000e+00],
       [6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00,
        0.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 0.0000000e+00,
        0.0000000e+00],
       [7.8013110e+04, 1.2159755e+05, 2.6434606e+05, 0.0000000e+00,
        0.0000000e+00],
       [2.3640930e+04, 9.6189630e+04, 1.4800111e+05, 0.0000000e+00,
        0.0000000e+00],
       [7.6253860e+04, 1.1386730e+05, 2.9866447e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.5505730e+04, 1.2738230e+05, 3.5534170e+04, 0.0000000e+00,
        1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00,
        0.0000000e+00],
       [6.4664710e+04, 1.3955316e+05, 1.3796262e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00,
        1.0000000e+00],
       [9.4657160e+04, 1.4507758e+05, 2.8257431e+05, 0.0000000e+00,
        1.0000000e+00],
       [2.8754330e+04, 1.1854605e+05, 1.7279567e+05, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 1.1698380e+05, 4.5173060e+04, 0.0000000e+00,
        0.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00,
        0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00,
        0.0000000e+00],
       [4.4069950e+04, 5.1283140e+04, 1.9702942e+05, 0.0000000e+00,
        0.0000000e+00],
       [7.7044010e+04, 9.9281340e+04, 1.4057481e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00,
        0.0000000e+00],
       [6.7532530e+04, 1.0575103e+05, 3.0476873e+05, 1.0000000e+00,
        0.0000000e+00],
       [2.8663760e+04, 1.2705621e+05, 2.0112682e+05, 1.0000000e+00,
        0.0000000e+00],
       [7.8389470e+04, 1.5377343e+05, 2.9973729e+05, 0.0000000e+00,
        1.0000000e+00],
       [8.6419700e+04, 1.5351411e+05, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00,
        0.0000000e+00],
       [3.8558510e+04, 8.2982090e+04, 1.7499930e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.3154600e+03, 1.1581621e+05, 2.9711446e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00,
        1.0000000e+00],
       [0.0000000e+00, 1.3542692e+05, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [2.2177740e+04, 1.5480614e+05, 2.8334720e+04, 0.0000000e+00,
        0.0000000e+00]])

In [18]:
regressor.coef_

array([[ 0.76394145,  0.04655444,  0.04389052,  0.28454473, -0.10738669]])

In [19]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D:434
Admin43434
Marketing 22344
State_flo 0 or 1:1
State_new 0 or 1:0

In [20]:
result=regressor.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [21]:
result

array([44556.1763731])